import unittest
from .extract_profile import get_profile


class TestProfileInference(unittest.TestCase):
    def testParameterized(self):
        for header, want in [
            ("asdf", None),  # Random garbage
            ("; Generated by Kiri:Moto\n", None),  # Header match but no profile
            ("; Generated by Kiri:Moto\n; Target: applesauce", None),  # Unknown profile
            ("; Generated by Kiri:Moto\n; Target: Creality.CR-30", "Creality CR30"),
            ("; Generated by Kiri:Moto\n; Target: Mini Prusa", "Prusa Mini"),
            ("; Generated by Kiri:Moto\n; Target: Delta V2", "Monoprice Mini Delta V2"),
        ]:
            with self.subTest(header=header, want=want):
                hdr = header.split("\n")
                result = get_profile(hdr)
                self.assertEqual(result, want)
